version: '3.8'

services:
  nuxt-prod:
    container_name: cepium_v2_front
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    container_name: cepium_v2_backend
    # конфигурация бэкенда
    networks:
      - app-net

networks:
  app-net:
    driver: bridge